// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service3CropHealth.proto

package jt.smartFarmingService3;

public interface cropHealthRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service3CropHealth.cropHealthRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.service3CropHealth.health health = 1;</code>
   */
  boolean hasHealth();
  /**
   * <code>.service3CropHealth.health health = 1;</code>
   */
  jt.smartFarmingService3.health getHealth();
  /**
   * <code>.service3CropHealth.health health = 1;</code>
   */
  jt.smartFarmingService3.healthOrBuilder getHealthOrBuilder();

  /**
   * <code>.service3CropHealth.water water = 2;</code>
   */
  boolean hasWater();
  /**
   * <code>.service3CropHealth.water water = 2;</code>
   */
  jt.smartFarmingService3.water getWater();
  /**
   * <code>.service3CropHealth.water water = 2;</code>
   */
  jt.smartFarmingService3.waterOrBuilder getWaterOrBuilder();

  /**
   * <code>.service3CropHealth.soil soil = 3;</code>
   */
  boolean hasSoil();
  /**
   * <code>.service3CropHealth.soil soil = 3;</code>
   */
  jt.smartFarmingService3.soil getSoil();
  /**
   * <code>.service3CropHealth.soil soil = 3;</code>
   */
  jt.smartFarmingService3.soilOrBuilder getSoilOrBuilder();
}
