// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service3CropHealth.proto

package jt.smartFarmingService3;

public interface cropHealthResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service3CropHealth.cropHealthResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string healthResponse = 1;</code>
   */
  java.lang.String getHealthResponse();
  /**
   * <code>string healthResponse = 1;</code>
   */
  com.google.protobuf.ByteString
      getHealthResponseBytes();

  /**
   * <code>string waterResponse = 2;</code>
   */
  java.lang.String getWaterResponse();
  /**
   * <code>string waterResponse = 2;</code>
   */
  com.google.protobuf.ByteString
      getWaterResponseBytes();

  /**
   * <code>string soilResponse = 3;</code>
   */
  java.lang.String getSoilResponse();
  /**
   * <code>string soilResponse = 3;</code>
   */
  com.google.protobuf.ByteString
      getSoilResponseBytes();
}
