// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service3CropHealth.proto

package jt.smartFarmingService3;

public interface growthOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service3CropHealth.growth)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 growth_level = 1;</code>
   */
  int getGrowthLevel();
}
