// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service3CropHealth.proto

package jt.smartFarmingService3;

public interface healthOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service3CropHealth.health)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string health_condition = 1;</code>
   */
  java.lang.String getHealthCondition();
  /**
   * <code>string health_condition = 1;</code>
   */
  com.google.protobuf.ByteString
      getHealthConditionBytes();
}
