// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service3CropHealth.proto

package jt.smartFarmingService3;

/**
 * Protobuf type {@code service3CropHealth.infestationRequest}
 */
public  final class infestationRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:service3CropHealth.infestationRequest)
    infestationRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use infestationRequest.newBuilder() to construct.
  private infestationRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private infestationRequest() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private infestationRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            jt.smartFarmingService3.growth.Builder subBuilder = null;
            if (growth_ != null) {
              subBuilder = growth_.toBuilder();
            }
            growth_ = input.readMessage(jt.smartFarmingService3.growth.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(growth_);
              growth_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            jt.smartFarmingService3.infestation.Builder subBuilder = null;
            if (infestationLevel_ != null) {
              subBuilder = infestationLevel_.toBuilder();
            }
            infestationLevel_ = input.readMessage(jt.smartFarmingService3.infestation.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(infestationLevel_);
              infestationLevel_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return jt.smartFarmingService3.Service3CropHealthImpl.internal_static_service3CropHealth_infestationRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return jt.smartFarmingService3.Service3CropHealthImpl.internal_static_service3CropHealth_infestationRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            jt.smartFarmingService3.infestationRequest.class, jt.smartFarmingService3.infestationRequest.Builder.class);
  }

  public static final int GROWTH_FIELD_NUMBER = 1;
  private jt.smartFarmingService3.growth growth_;
  /**
   * <code>.service3CropHealth.growth growth = 1;</code>
   */
  public boolean hasGrowth() {
    return growth_ != null;
  }
  /**
   * <code>.service3CropHealth.growth growth = 1;</code>
   */
  public jt.smartFarmingService3.growth getGrowth() {
    return growth_ == null ? jt.smartFarmingService3.growth.getDefaultInstance() : growth_;
  }
  /**
   * <code>.service3CropHealth.growth growth = 1;</code>
   */
  public jt.smartFarmingService3.growthOrBuilder getGrowthOrBuilder() {
    return getGrowth();
  }

  public static final int INFESTATIONLEVEL_FIELD_NUMBER = 2;
  private jt.smartFarmingService3.infestation infestationLevel_;
  /**
   * <code>.service3CropHealth.infestation infestationLevel = 2;</code>
   */
  public boolean hasInfestationLevel() {
    return infestationLevel_ != null;
  }
  /**
   * <code>.service3CropHealth.infestation infestationLevel = 2;</code>
   */
  public jt.smartFarmingService3.infestation getInfestationLevel() {
    return infestationLevel_ == null ? jt.smartFarmingService3.infestation.getDefaultInstance() : infestationLevel_;
  }
  /**
   * <code>.service3CropHealth.infestation infestationLevel = 2;</code>
   */
  public jt.smartFarmingService3.infestationOrBuilder getInfestationLevelOrBuilder() {
    return getInfestationLevel();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (growth_ != null) {
      output.writeMessage(1, getGrowth());
    }
    if (infestationLevel_ != null) {
      output.writeMessage(2, getInfestationLevel());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (growth_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getGrowth());
    }
    if (infestationLevel_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getInfestationLevel());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof jt.smartFarmingService3.infestationRequest)) {
      return super.equals(obj);
    }
    jt.smartFarmingService3.infestationRequest other = (jt.smartFarmingService3.infestationRequest) obj;

    boolean result = true;
    result = result && (hasGrowth() == other.hasGrowth());
    if (hasGrowth()) {
      result = result && getGrowth()
          .equals(other.getGrowth());
    }
    result = result && (hasInfestationLevel() == other.hasInfestationLevel());
    if (hasInfestationLevel()) {
      result = result && getInfestationLevel()
          .equals(other.getInfestationLevel());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasGrowth()) {
      hash = (37 * hash) + GROWTH_FIELD_NUMBER;
      hash = (53 * hash) + getGrowth().hashCode();
    }
    if (hasInfestationLevel()) {
      hash = (37 * hash) + INFESTATIONLEVEL_FIELD_NUMBER;
      hash = (53 * hash) + getInfestationLevel().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static jt.smartFarmingService3.infestationRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static jt.smartFarmingService3.infestationRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static jt.smartFarmingService3.infestationRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static jt.smartFarmingService3.infestationRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static jt.smartFarmingService3.infestationRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static jt.smartFarmingService3.infestationRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static jt.smartFarmingService3.infestationRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static jt.smartFarmingService3.infestationRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static jt.smartFarmingService3.infestationRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static jt.smartFarmingService3.infestationRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static jt.smartFarmingService3.infestationRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static jt.smartFarmingService3.infestationRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(jt.smartFarmingService3.infestationRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code service3CropHealth.infestationRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:service3CropHealth.infestationRequest)
      jt.smartFarmingService3.infestationRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return jt.smartFarmingService3.Service3CropHealthImpl.internal_static_service3CropHealth_infestationRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return jt.smartFarmingService3.Service3CropHealthImpl.internal_static_service3CropHealth_infestationRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              jt.smartFarmingService3.infestationRequest.class, jt.smartFarmingService3.infestationRequest.Builder.class);
    }

    // Construct using jt.smartFarmingService3.infestationRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (growthBuilder_ == null) {
        growth_ = null;
      } else {
        growth_ = null;
        growthBuilder_ = null;
      }
      if (infestationLevelBuilder_ == null) {
        infestationLevel_ = null;
      } else {
        infestationLevel_ = null;
        infestationLevelBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return jt.smartFarmingService3.Service3CropHealthImpl.internal_static_service3CropHealth_infestationRequest_descriptor;
    }

    @java.lang.Override
    public jt.smartFarmingService3.infestationRequest getDefaultInstanceForType() {
      return jt.smartFarmingService3.infestationRequest.getDefaultInstance();
    }

    @java.lang.Override
    public jt.smartFarmingService3.infestationRequest build() {
      jt.smartFarmingService3.infestationRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public jt.smartFarmingService3.infestationRequest buildPartial() {
      jt.smartFarmingService3.infestationRequest result = new jt.smartFarmingService3.infestationRequest(this);
      if (growthBuilder_ == null) {
        result.growth_ = growth_;
      } else {
        result.growth_ = growthBuilder_.build();
      }
      if (infestationLevelBuilder_ == null) {
        result.infestationLevel_ = infestationLevel_;
      } else {
        result.infestationLevel_ = infestationLevelBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof jt.smartFarmingService3.infestationRequest) {
        return mergeFrom((jt.smartFarmingService3.infestationRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(jt.smartFarmingService3.infestationRequest other) {
      if (other == jt.smartFarmingService3.infestationRequest.getDefaultInstance()) return this;
      if (other.hasGrowth()) {
        mergeGrowth(other.getGrowth());
      }
      if (other.hasInfestationLevel()) {
        mergeInfestationLevel(other.getInfestationLevel());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      jt.smartFarmingService3.infestationRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (jt.smartFarmingService3.infestationRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private jt.smartFarmingService3.growth growth_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        jt.smartFarmingService3.growth, jt.smartFarmingService3.growth.Builder, jt.smartFarmingService3.growthOrBuilder> growthBuilder_;
    /**
     * <code>.service3CropHealth.growth growth = 1;</code>
     */
    public boolean hasGrowth() {
      return growthBuilder_ != null || growth_ != null;
    }
    /**
     * <code>.service3CropHealth.growth growth = 1;</code>
     */
    public jt.smartFarmingService3.growth getGrowth() {
      if (growthBuilder_ == null) {
        return growth_ == null ? jt.smartFarmingService3.growth.getDefaultInstance() : growth_;
      } else {
        return growthBuilder_.getMessage();
      }
    }
    /**
     * <code>.service3CropHealth.growth growth = 1;</code>
     */
    public Builder setGrowth(jt.smartFarmingService3.growth value) {
      if (growthBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        growth_ = value;
        onChanged();
      } else {
        growthBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.service3CropHealth.growth growth = 1;</code>
     */
    public Builder setGrowth(
        jt.smartFarmingService3.growth.Builder builderForValue) {
      if (growthBuilder_ == null) {
        growth_ = builderForValue.build();
        onChanged();
      } else {
        growthBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.service3CropHealth.growth growth = 1;</code>
     */
    public Builder mergeGrowth(jt.smartFarmingService3.growth value) {
      if (growthBuilder_ == null) {
        if (growth_ != null) {
          growth_ =
            jt.smartFarmingService3.growth.newBuilder(growth_).mergeFrom(value).buildPartial();
        } else {
          growth_ = value;
        }
        onChanged();
      } else {
        growthBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.service3CropHealth.growth growth = 1;</code>
     */
    public Builder clearGrowth() {
      if (growthBuilder_ == null) {
        growth_ = null;
        onChanged();
      } else {
        growth_ = null;
        growthBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.service3CropHealth.growth growth = 1;</code>
     */
    public jt.smartFarmingService3.growth.Builder getGrowthBuilder() {
      
      onChanged();
      return getGrowthFieldBuilder().getBuilder();
    }
    /**
     * <code>.service3CropHealth.growth growth = 1;</code>
     */
    public jt.smartFarmingService3.growthOrBuilder getGrowthOrBuilder() {
      if (growthBuilder_ != null) {
        return growthBuilder_.getMessageOrBuilder();
      } else {
        return growth_ == null ?
            jt.smartFarmingService3.growth.getDefaultInstance() : growth_;
      }
    }
    /**
     * <code>.service3CropHealth.growth growth = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        jt.smartFarmingService3.growth, jt.smartFarmingService3.growth.Builder, jt.smartFarmingService3.growthOrBuilder> 
        getGrowthFieldBuilder() {
      if (growthBuilder_ == null) {
        growthBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            jt.smartFarmingService3.growth, jt.smartFarmingService3.growth.Builder, jt.smartFarmingService3.growthOrBuilder>(
                getGrowth(),
                getParentForChildren(),
                isClean());
        growth_ = null;
      }
      return growthBuilder_;
    }

    private jt.smartFarmingService3.infestation infestationLevel_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        jt.smartFarmingService3.infestation, jt.smartFarmingService3.infestation.Builder, jt.smartFarmingService3.infestationOrBuilder> infestationLevelBuilder_;
    /**
     * <code>.service3CropHealth.infestation infestationLevel = 2;</code>
     */
    public boolean hasInfestationLevel() {
      return infestationLevelBuilder_ != null || infestationLevel_ != null;
    }
    /**
     * <code>.service3CropHealth.infestation infestationLevel = 2;</code>
     */
    public jt.smartFarmingService3.infestation getInfestationLevel() {
      if (infestationLevelBuilder_ == null) {
        return infestationLevel_ == null ? jt.smartFarmingService3.infestation.getDefaultInstance() : infestationLevel_;
      } else {
        return infestationLevelBuilder_.getMessage();
      }
    }
    /**
     * <code>.service3CropHealth.infestation infestationLevel = 2;</code>
     */
    public Builder setInfestationLevel(jt.smartFarmingService3.infestation value) {
      if (infestationLevelBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        infestationLevel_ = value;
        onChanged();
      } else {
        infestationLevelBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.service3CropHealth.infestation infestationLevel = 2;</code>
     */
    public Builder setInfestationLevel(
        jt.smartFarmingService3.infestation.Builder builderForValue) {
      if (infestationLevelBuilder_ == null) {
        infestationLevel_ = builderForValue.build();
        onChanged();
      } else {
        infestationLevelBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.service3CropHealth.infestation infestationLevel = 2;</code>
     */
    public Builder mergeInfestationLevel(jt.smartFarmingService3.infestation value) {
      if (infestationLevelBuilder_ == null) {
        if (infestationLevel_ != null) {
          infestationLevel_ =
            jt.smartFarmingService3.infestation.newBuilder(infestationLevel_).mergeFrom(value).buildPartial();
        } else {
          infestationLevel_ = value;
        }
        onChanged();
      } else {
        infestationLevelBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.service3CropHealth.infestation infestationLevel = 2;</code>
     */
    public Builder clearInfestationLevel() {
      if (infestationLevelBuilder_ == null) {
        infestationLevel_ = null;
        onChanged();
      } else {
        infestationLevel_ = null;
        infestationLevelBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.service3CropHealth.infestation infestationLevel = 2;</code>
     */
    public jt.smartFarmingService3.infestation.Builder getInfestationLevelBuilder() {
      
      onChanged();
      return getInfestationLevelFieldBuilder().getBuilder();
    }
    /**
     * <code>.service3CropHealth.infestation infestationLevel = 2;</code>
     */
    public jt.smartFarmingService3.infestationOrBuilder getInfestationLevelOrBuilder() {
      if (infestationLevelBuilder_ != null) {
        return infestationLevelBuilder_.getMessageOrBuilder();
      } else {
        return infestationLevel_ == null ?
            jt.smartFarmingService3.infestation.getDefaultInstance() : infestationLevel_;
      }
    }
    /**
     * <code>.service3CropHealth.infestation infestationLevel = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        jt.smartFarmingService3.infestation, jt.smartFarmingService3.infestation.Builder, jt.smartFarmingService3.infestationOrBuilder> 
        getInfestationLevelFieldBuilder() {
      if (infestationLevelBuilder_ == null) {
        infestationLevelBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            jt.smartFarmingService3.infestation, jt.smartFarmingService3.infestation.Builder, jt.smartFarmingService3.infestationOrBuilder>(
                getInfestationLevel(),
                getParentForChildren(),
                isClean());
        infestationLevel_ = null;
      }
      return infestationLevelBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:service3CropHealth.infestationRequest)
  }

  // @@protoc_insertion_point(class_scope:service3CropHealth.infestationRequest)
  private static final jt.smartFarmingService3.infestationRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new jt.smartFarmingService3.infestationRequest();
  }

  public static jt.smartFarmingService3.infestationRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<infestationRequest>
      PARSER = new com.google.protobuf.AbstractParser<infestationRequest>() {
    @java.lang.Override
    public infestationRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new infestationRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<infestationRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<infestationRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public jt.smartFarmingService3.infestationRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

