// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service3CropHealth.proto

package jt.smartFarmingService3;

public interface infestationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service3CropHealth.infestationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.service3CropHealth.growth growth = 1;</code>
   */
  boolean hasGrowth();
  /**
   * <code>.service3CropHealth.growth growth = 1;</code>
   */
  jt.smartFarmingService3.growth getGrowth();
  /**
   * <code>.service3CropHealth.growth growth = 1;</code>
   */
  jt.smartFarmingService3.growthOrBuilder getGrowthOrBuilder();

  /**
   * <code>.service3CropHealth.infestation infestationLevel = 2;</code>
   */
  boolean hasInfestationLevel();
  /**
   * <code>.service3CropHealth.infestation infestationLevel = 2;</code>
   */
  jt.smartFarmingService3.infestation getInfestationLevel();
  /**
   * <code>.service3CropHealth.infestation infestationLevel = 2;</code>
   */
  jt.smartFarmingService3.infestationOrBuilder getInfestationLevelOrBuilder();
}
