// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service3CropHealth.proto

package jt.smartFarmingService3;

public interface infestationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service3CropHealth.infestation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 infestation = 2;</code>
   */
  int getInfestation();
}
