// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service3CropHealth.proto

package jt.smartFarmingService3;

public interface infestationResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service3CropHealth.infestationResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string growthResponse = 1;</code>
   */
  java.lang.String getGrowthResponse();
  /**
   * <code>string growthResponse = 1;</code>
   */
  com.google.protobuf.ByteString
      getGrowthResponseBytes();

  /**
   * <code>string infestationLevelResponse = 2;</code>
   */
  java.lang.String getInfestationLevelResponse();
  /**
   * <code>string infestationLevelResponse = 2;</code>
   */
  com.google.protobuf.ByteString
      getInfestationLevelResponseBytes();
}
