// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service3CropHealth.proto

package jt.smartFarmingService3;

public final class Service3CropHealthImpl {
  private Service3CropHealthImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service3CropHealth_health_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service3CropHealth_health_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service3CropHealth_water_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service3CropHealth_water_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service3CropHealth_soil_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service3CropHealth_soil_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service3CropHealth_cropHealthRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service3CropHealth_cropHealthRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service3CropHealth_cropHealthResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service3CropHealth_cropHealthResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service3CropHealth_growth_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service3CropHealth_growth_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service3CropHealth_infestation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service3CropHealth_infestation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service3CropHealth_infestationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service3CropHealth_infestationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service3CropHealth_infestationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service3CropHealth_infestationResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030Service3CropHealth.proto\022\022service3Crop" +
      "Health\"\"\n\006health\022\030\n\020health_condition\030\001 \001" +
      "(\t\"\034\n\005water\022\023\n\013water_level\030\002 \001(\t\"\036\n\004soil" +
      "\022\026\n\016soil_condition\030\003 \001(\t\"\221\001\n\021cropHealthR" +
      "equest\022*\n\006health\030\001 \001(\0132\032.service3CropHea" +
      "lth.health\022(\n\005water\030\002 \001(\0132\031.service3Crop" +
      "Health.water\022&\n\004soil\030\003 \001(\0132\030.service3Cro" +
      "pHealth.soil\"Y\n\022cropHealthResponse\022\026\n\016he" +
      "althResponse\030\001 \001(\t\022\025\n\rwaterResponse\030\002 \001(" +
      "\t\022\024\n\014soilResponse\030\003 \001(\t\"\036\n\006growth\022\024\n\014gro" +
      "wth_level\030\001 \001(\005\"\"\n\013infestation\022\023\n\013infest" +
      "ation\030\002 \001(\005\"{\n\022infestationRequest\022*\n\006gro" +
      "wth\030\001 \001(\0132\032.service3CropHealth.growth\0229\n" +
      "\020infestationLevel\030\002 \001(\0132\037.service3CropHe" +
      "alth.infestation\"O\n\023infestationResponse\022" +
      "\026\n\016growthResponse\030\001 \001(\t\022 \n\030infestationLe" +
      "velResponse\030\002 \001(\t2\342\001\n\022CropHealthService3" +
      "\022_\n\ncropHealth\022%.service3CropHealth.crop" +
      "HealthRequest\032&.service3CropHealth.cropH" +
      "ealthResponse\"\0000\001\022k\n\024cropInfestationLeve" +
      "l\022&.service3CropHealth.infestationReques" +
      "t\032\'.service3CropHealth.infestationRespon" +
      "se\"\000(\001B3\n\027jt.smartFarmingService3B\026Servi" +
      "ce3CropHealthImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_service3CropHealth_health_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_service3CropHealth_health_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service3CropHealth_health_descriptor,
        new java.lang.String[] { "HealthCondition", });
    internal_static_service3CropHealth_water_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_service3CropHealth_water_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service3CropHealth_water_descriptor,
        new java.lang.String[] { "WaterLevel", });
    internal_static_service3CropHealth_soil_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_service3CropHealth_soil_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service3CropHealth_soil_descriptor,
        new java.lang.String[] { "SoilCondition", });
    internal_static_service3CropHealth_cropHealthRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_service3CropHealth_cropHealthRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service3CropHealth_cropHealthRequest_descriptor,
        new java.lang.String[] { "Health", "Water", "Soil", });
    internal_static_service3CropHealth_cropHealthResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_service3CropHealth_cropHealthResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service3CropHealth_cropHealthResponse_descriptor,
        new java.lang.String[] { "HealthResponse", "WaterResponse", "SoilResponse", });
    internal_static_service3CropHealth_growth_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_service3CropHealth_growth_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service3CropHealth_growth_descriptor,
        new java.lang.String[] { "GrowthLevel", });
    internal_static_service3CropHealth_infestation_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_service3CropHealth_infestation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service3CropHealth_infestation_descriptor,
        new java.lang.String[] { "Infestation", });
    internal_static_service3CropHealth_infestationRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_service3CropHealth_infestationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service3CropHealth_infestationRequest_descriptor,
        new java.lang.String[] { "Growth", "InfestationLevel", });
    internal_static_service3CropHealth_infestationResponse_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_service3CropHealth_infestationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service3CropHealth_infestationResponse_descriptor,
        new java.lang.String[] { "GrowthResponse", "InfestationLevelResponse", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
