// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service3CropHealth.proto

package jt.smartFarmingService3;

public interface soilOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service3CropHealth.soil)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string soil_condition = 3;</code>
   */
  java.lang.String getSoilCondition();
  /**
   * <code>string soil_condition = 3;</code>
   */
  com.google.protobuf.ByteString
      getSoilConditionBytes();
}
