// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service3CropHealth.proto

package jt.smartFarmingService3;

public interface waterOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service3CropHealth.water)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string water_level = 2;</code>
   */
  java.lang.String getWaterLevel();
  /**
   * <code>string water_level = 2;</code>
   */
  com.google.protobuf.ByteString
      getWaterLevelBytes();
}
