// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service1Livestock.proto

package jt.smartFarmingService1;

public interface HeartRateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service1LiveStock.HeartRateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string rate = 1;</code>
   */
  java.lang.String getRate();
  /**
   * <code>string rate = 1;</code>
   */
  com.google.protobuf.ByteString
      getRateBytes();
}
