// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service1Livestock.proto

package jt.smartFarmingService1;

public interface HeartrateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service1LiveStock.Heartrate)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string heart_rate = 1;</code>
   */
  java.lang.String getHeartRate();
  /**
   * <code>string heart_rate = 1;</code>
   */
  com.google.protobuf.ByteString
      getHeartRateBytes();
}
