// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service1Livestock.proto

package jt.smartFarmingService1;

public interface HeartRateResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service1LiveStock.HeartRateResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double rateResponse = 1;</code>
   */
  double getRateResponse();
}
