// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service1Livestock.proto

package jt.smartFarmingService1;

public final class Service1LiveStockImpl {
  private Service1LiveStockImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1LiveStock_HeartRateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1LiveStock_HeartRateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1LiveStock_HeartRateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1LiveStock_HeartRateResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027Service1Livestock.proto\022\021service1LiveS" +
      "tock\" \n\020HeartRateRequest\022\014\n\004rate\030\001 \001(\t\")" +
      "\n\021HeartRateResponse\022\024\n\014rateResponse\030\001 \001(" +
      "\0012p\n\021LiveStockService1\022[\n\014getHeartRate\022#" +
      ".service1LiveStock.HeartRateRequest\032$.se" +
      "rvice1LiveStock.HeartRateResponse\"\000B2\n\027j" +
      "t.smartFarmingService1B\025Service1LiveStoc" +
      "kImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_service1LiveStock_HeartRateRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_service1LiveStock_HeartRateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1LiveStock_HeartRateRequest_descriptor,
        new java.lang.String[] { "Rate", });
    internal_static_service1LiveStock_HeartRateResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_service1LiveStock_HeartRateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1LiveStock_HeartRateResponse_descriptor,
        new java.lang.String[] { "RateResponse", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
