// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service2Climate.proto

package jt.smartFarmingService2;

public interface ClimateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service2Climate.ClimateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.service2Climate.rainfall rainfallRequest = 1;</code>
   */
  boolean hasRainfallRequest();
  /**
   * <code>.service2Climate.rainfall rainfallRequest = 1;</code>
   */
  jt.smartFarmingService2.rainfall getRainfallRequest();
  /**
   * <code>.service2Climate.rainfall rainfallRequest = 1;</code>
   */
  jt.smartFarmingService2.rainfallOrBuilder getRainfallRequestOrBuilder();

  /**
   * <code>.service2Climate.temperature temperatureRequest = 2;</code>
   */
  boolean hasTemperatureRequest();
  /**
   * <code>.service2Climate.temperature temperatureRequest = 2;</code>
   */
  jt.smartFarmingService2.temperature getTemperatureRequest();
  /**
   * <code>.service2Climate.temperature temperatureRequest = 2;</code>
   */
  jt.smartFarmingService2.temperatureOrBuilder getTemperatureRequestOrBuilder();
}
