// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service2Climate.proto

package jt.smartFarmingService2;

public interface ClimateResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service2Climate.ClimateResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string rianfallResponse = 1;</code>
   */
  java.lang.String getRianfallResponse();
  /**
   * <code>string rianfallResponse = 1;</code>
   */
  com.google.protobuf.ByteString
      getRianfallResponseBytes();

  /**
   * <code>string temperatureResponse = 2;</code>
   */
  java.lang.String getTemperatureResponse();
  /**
   * <code>string temperatureResponse = 2;</code>
   */
  com.google.protobuf.ByteString
      getTemperatureResponseBytes();
}
