// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service2Climate.proto

package jt.smartFarmingService2;

public interface rainfallOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service2Climate.rainfall)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 rainfall = 1;</code>
   */
  int getRainfall();
}
