// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service2Climate.proto

package jt.smartFarmingService2;

public interface temperatureOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service2Climate.temperature)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 temperature_degree = 2;</code>
   */
  int getTemperatureDegree();
}
